############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://github.com/Dazmk/hexo-theme-material-x
  cdn: # 把对应的那一行注释掉就使用本地的文件
    css:
      style: https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/css/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/js/app.js
      search: https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/js/search.js
      volantis: https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/js/volantis.min.js

############################### 主题风格 ###############################
style: material    # material: 导航栏和标题栏背景是主题色
# style: pure        # pure: 导航栏和标题栏背景是白色


############################### 服务开关 ###############################
scrollreveal: true
nodewaves: true
busuanzi: true
fastclick: true
# Less渲染
less:
  compress: true
# 文章字数
word_count: true


############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: true      # 是否启用
  color: '#242424'  # 主题色
  mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease     # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
  # url: https://music.163.com/#/playlist?id=974541219
  id: 2868600326       # 歌曲/专辑/歌单 ID
  volume: 0.7       # 音量, 0~1
  autoplay: false   # 自动播放

# 友链页头像占位图
avatar_placeholder: https://s1.ax1x.com/2020/09/10/w8ffsK.jpg

# 日期格式 http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # 文章发布日期的格式
updated_date_format: 'll' # 文章更新日期的格式

# 幻灯片
backstretch:
  position: cover  # cover: 封面背景   full: 整个网页背景
  duration: 60000 # 持续时间（毫秒）
  fade: 1000     # 渐变（毫秒）
  images:
    - https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/img/gb3.jpg
    # - https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/img/jxjy.jpg
    # - https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/img/gd.jpg
    # - https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/img/stzz.jpg
    # - https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/img/gd2.jpg
    # - https://cdn.jsdelivr.net/gh/yangyfeng/yangyfeng.github.io@gh-pages/assets_blog/img/jxjy2.jpg

rss: ./atom.xml
############################### 自定义 ###############################
# page的封面
cover:
  # 后期将会提供多种封面方案
  scheme: search    
  # full（默认值）: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  # height: full    
  # logo和title只显示一个，若同时设置，则只显示logo 
  title: 漫道求索
  # logo: assets/logo.png    
  search_placeholder: 这里有你知道的一切

  # 主页封面菜单
  features:
    - name: 主页
      icon: fas fa-home
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: blogpost/categories/
      rel: nofollow
    - name: 标签
      icon: fas fa-hashtag
      url: blogpost/tags/
      rel: nofollow
    - name: 归档
      icon: fas fa-archive
      url: blogpost/archives/
      rel: nofollow
    - name: 朋友
      icon: fas fa-user-friends
      url: friends/
      rel: nofollow
    - name: 关于
      icon: fas fa-info-circle
      url: about/
      rel: nofollow

# 桌面端导航栏菜单
menu_desktop:
  - name: 主页
    icon: fas fa-home
    url: /
  - name: 分类
    icon: fas fa-folder-open
    url: blogpost/categories/
    rel: nofollow
  - name: 标签
    icon: fas fa-hashtag
    url: blogpost/tags/
    rel: nofollow
  - name: 归档
    icon: fas fa-archive
    url: blogpost/archives/
    rel: nofollow
  - name: 朋友
    icon: fas fa-user-friends
    url: friends/
    rel: nofollow
  - name: 关于
    icon: fas fa-info-circle
    url: about/
    rel: nofollow

# 手机端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  - name: 所有文章
    icon: fas fa-clock
    url: /
  - name: 文章归档
    icon: fas fa-archive
    url: blogpost/archives/
    rel: nofollow
  - name: 所有标签
    icon: fas fa-hashtag
    url: blogpost/tags/
    rel: nofollow
  - name: 我的友链
    icon: fas fa-link
    url: friends/
    rel: nofollow
  - name: RSS订阅
    icon: fas fa-rss
    url: ./atom.xml
    rel: nofollow
  - name: 关于博主
    icon: fas fa-info-circle
    url: about/
    rel: nofollow

# 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
# 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
# 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
meta:
  header: [title, author, date, categories, counter, top]
  footer: [updated, tags, share]

# 主体元素，你也可以在页面的Front-matter中设置
body: [article, comments]

# 侧边栏小部件，默认按下面给定的顺序全部显示，文章中还可以自定义显示一部分以及顺序
sidebar:
  - widget: author
    title: 漫道求索
    body: '<span data-chakhsu data-chakhsu-text="每写一行代码，都是人类的一次进步">每写一行代码，都是人类的一次进步</span>'
    avatar: https://s2.ax1x.com/2019/07/12/Zhm4jf.jpg
    social: true

  - widget: grid
    icon: fas fa-map-signs
    title: 站内导航
    rows:
      - name: 所有文章
        icon: fas fa-clock
        url: /
      - name: 文章归档
        icon: fas fa-archive
        url: blogpost/archives/
        rel: nofollow
      - name: 所有标签
        icon: fas fa-hashtag
        url: blogpost/tags/
        rel: nofollow
      - name: 我的友链
        icon: fas fa-link
        url: friends/
        rel: nofollow
      - name: RSS订阅
        icon: fas fa-rss
        url: ./atom.xml
        rel: nofollow
      - name: 关于博主
        icon: fas fa-info-circle
        url: about/
        rel: nofollow

  - widget: category
    more:
      icon: fas fa-expand-arrows-alt
      url: blogpost/categories/
      rel: nofollow

  - widget: tagcloud
    icon: fas fa-fire
    more:
      icon: fas fa-expand-arrows-alt
      url: blogpost/tags/
      rel: nofollow

  - widget: related_posts # 需要安装插件  npm i -S hexo-related-popular-posts

  - widget: music
    icon: fas fa-compact-disc
    title: 最近在听
    more:
      icon: far fa-heart
      rel: external nofollow noopener noreferrer
      url: https://music.163.com/#/user/home?id=629541737
      target: _blank
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 2868600326     # 歌曲/专辑/歌单 ID

# 社交信息
social:
  # 邮箱
  - icon: fas fa-envelope
    url: mailto:yangyufeng.web@foxmail.com
  # 思否
  - icon: fas fa-link
    url: https://segmentfault.com/u/yangyufeng
  # csdn
  - icon: fa fa-paper-plane
    url: https://blog.csdn.net/qq_35676160
  # 工具箱
  - icon: fas fa-toolbox
    url: https://tool.lu/

# 分享按钮
# 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQ好友
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQ空间
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  - id: weibo
    name: 微博
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  - id: qrcode
    name: 微信
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: qrcode
    name: QRcode
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png



# footer: ''


############################### 评论系统 ###############################
# disqus_shortname: 要使用哪个请复制到根目录配置文件！
# livere_uid: 要使用哪个请复制到根目录配置文件！
# gitalk: 要使用哪个请复制到根目录配置文件！
#   clientID: 你的clientID
#   clientSecret: 你的clientSecret
#   repo: 你的repo名
#   owner: 你的GitHub名
#   admin: [] 至少填写你的GitHub名
# leancloud: 要使用哪个请复制到根目录配置文件！
#   app_id: 你的appId
#   app_key: 你的appKey

#gitalk settings
gitalk:
  enable: true #用来做启用判断可以不用
  owner: yangyfeng  #Github 用户名,
  repo:  yangyfeng.github.io #储存评论issue的github仓库名
  admin: yangyfeng  #Github 用户名,
  clientID: c9d3bfe9137dc2038a1a #`Github Application clientID`
  clientSecret: 1ecb6999a152dad80e08c672ac5a779b92eb6ec0 #`Github Application clientSecret`

############################### 杂项，请勿删除 ###############################
#valine配置
valine:
  enable: false # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:
